<?php echo $this->doctype(); ?>

<html lang="pt_BR">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Administração') ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
            ->prependStylesheet($this->basePath() . '/componentes/datepicker/css/smoothness/jquery-ui-1.10.2.custom.css')
            ->prependStylesheet($this->basePath() . '/css/admin.css')
            ->prependStylesheet($this->basePath() . '/css/style_admin.css')
            ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
            ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/inputmask-plugin.js')
            ->prependFile($this->basePath() . '/componentes/tinymce/js/tinymce/tinymce.min.js')
            ->prependFile($this->basePath() . '/componentes/datepicker/development-bundle/ui/minified/i18n/jquery.ui.datepicker-pt-BR.min.js')
            ->prependFile($this->basePath() . '/componentes/datepicker/js/jquery-ui-1.10.2.custom.js')
            ->prependFile($this->basePath() . '/js/funcoes.js')
            ->prependFile($this->basePath() . '/js/maskedinput.js')
            ->prependFile($this->basePath() . '/js/jquery.min.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>
        <script>
            tinymce.init({
                selector:'textarea.formatacao',
                menubar : false
            });

            tinymce.init({
                selector:'textarea.formatacaoi',
                menubar : false
            });
        </script>

        <script>
            $(function($){

                $(".data" ).datepicker({
                    showOtherMonths: true,
                    selectOtherMonths: true,

                    regional:'br'
                });
            });
        </script>

        <style type="text/css">
            input{
                border:1px solid #060;
            }
            a.link_branco:link {
                color:#FFF;
                text-decoration: none;
            }
            a.link_branco:visited {
                text-decoration: none;
                color:#FFF;
            }
            a.link_branco:hover {
                text-decoration: none;
                color:#FFF;
            }
            a.link_branco:active {
                text-decoration: none;
                color:#FFF;
            }
        </style>

    </head>
    <body>
    <div class="topo_base" align="center">
        <div class="topo_" align="center">
            <div class="topo" align="center" style="">
                <div style="max-width:1000px;">
                    <?php if($this->identity()):?>
                    <a href="<?php echo $this->url('admin-home') ?>"><div class="logo"></div></a>

                    <div style="float:right; text-align:right; padding:10px; padding-top:5px; color:#069; ">
                        <span class="subTitulo">Painel Administrativo</span><br />
            <span class="textoNormalEscuro">
                            Olá <strong>Administrador</strong>, bem vindo(a) ao painel administrativo.<br />
              <a style="color:#000;"  href="<?php echo $this->url('admin-logout') ?>">Clique aqui</a> para desconectar.             </span>
                    </div>
                    <?php else:?>
                        <a href="<?php echo $this->url('admin-auth') ?>"><div class="logo"></div></a>

                                <div style="float:right; text-align:right; padding:10px; padding-top:5px; color:#069; ">
                                    <span class="subTitulo">Painel Administrativo</span><br />

                                </div>
                    <?php endif;?>
                </div>
            </div>
        </div>
    </div>

    <br />
    <table width="100%">
        <tr>
            <td colspan="3" >
                <div style=" margin:20px; margin-top:0px;">

                    <table width="100%" border="0" cellspacing="0" cellpadding="12">
                        <tr>
                            <td width="200" align="left" valign="top">
                                <?php if($this->identity()):?>


                                <strong>Ofertas</strong><br />
                                <a href="<?php echo $this->url('admin-clientes') ?>"><div class="menuAdm">Clientes</div></a>
                                <a href="<?php echo $this->url('admin-empresas') ?>"><div class="menuAdm">Empresas</div></a>
                                <a href="<?php echo $this->url('admin-ofertas') ?>"><div class="menuAdm">Ofertas</div></a>
                                <a href="<?php echo $this->url('admin-voucher') ?>"><div class="menuAdm">Voucher</div></a>
                                <a href="<?php echo $this->url('admin-desejos') ?>"><div class="menuAdm">Desejos</div></a>

                                <strong>Conteudo</strong><br />
                                <a href="<?php echo $this->url('admin-publicidades') ?>"><div class="menuAdm">Publicidades</div></a>

                                <strong>Avançado</strong><br />
                                <a href="<?php echo $this->url('admin-config') ?>"><div class="menuAdm">Configurações</div></a>
                                <a href="<?php echo $this->url('admin-usuarios') ?>"><div class="menuAdm">Usuários</div></a>
                                <a href="<?php echo $this->url('admin-admin') ?>"><div class="menuAdm">Administradores</div></a>


                                <?php endif; ?>

                            </td>
                            <td align="left" valign="top" style="padding:20px; ">
                                <?php echo $this->message(); ?><br>
                                <?php echo $this->content; ?>
                            </td>
                        </tr>
                    </table>

                </div>
            </td>
        </tr>
    </table>
    </body>
</html>