<div class="tabela_">
	<table width="100%" border="0" cellpadding="6" cellspacing="0" class="tabela">

		<tr>
			<td colspan="2" align="left"  class="subMenu">
				Usuários Cadastrados
			</td>
		</tr>
		<tr>
			<td colspan="2" align="left" valign="top" class="textoNormalEscuro">

				<table class="tabela" width="100%" border="0" cellspacing="0" cellpadding="3">
					
					<tr>
						<td>
							<a href="<?php echo $this->url('admin-admin/default', array('action' => 'inserir'))?>">
								Novo Administrador
							</a>
						</td>
					</tr>
					<tr>
						<td><span class="textoNormalEscuro"><strong>Cód</strong></span></td>
						<td><span class="textoNormalEscuro"><strong>Nome</strong></span></td>
						<td><span class="textoNormalEscuro"><strong>Login</strong></span></td>
						<td><span class="textoNormalEscuro"><strong>Cpf</strong></span></td>
						<td align="center"><span class="textoNormalEscuro"><strong>Opções</strong></span></td>
					</tr>
					<?php
					/**
					 * @var $entity \Admin\Entity\Admin
					 */
					if ($this->data):
						foreach ($this->data as $entity): ?>
							<tr>
								<td><?php echo $entity->getId(); ?></td>
								<td><?php echo $entity->getNome(); ?></td>
								<td><?php echo $entity->getLogin(); ?></td>
								<td><?php echo $entity->getCpf(); ?></td>
								<td>
									<a class="btn btn-xs btn-warning" title="Editar" href="<?php echo $this->url('admin-admin/default', array('action' => 'editar', 'id' => $entity->getId(),))?>"><span class="glyphicon glyphicon-edit"></span></a>
								    <a class="btn btn-xs btn-danger" title="Deletar" href="<?php echo $this->url('admin-admin/default', array("action" => "excluir", "id" => $entity->getId(),)); ?>"><span class="glyphicon glyphicon-floppy-remove"></span></a>

								</td>
							</tr>

					<?php endforeach;
						endif;?>

				</table>
				
			</td>
		</tr>


	</table>
</div>
<div style="clear:both;"></div>
<?php echo $this->paginationControl($this->data,'Sliding','partials/paginator', array('router' => 'admin-admin/paginator')); ?>


<?php $this->headScript()->captureStart(); ?>
$(function(){
// variável para conter a url deletar
var url_deletar     = '<?php echo $this->url('admin-admin/default', array("action" => "excluir")); ?>' + '/';

// qualquer link que tiver a url deletar vai sofrer um evento quando for clicada
$("a[href*='" + url_deletar + "']").click(function (event) {
// variável contendo o id referente ao botão clicado
var admin_id  = $(this).attr('href').split(url_deletar).pop();
// variável contendo mensagem da janela
var mensagem = "Deseja realmente apagar o Associado com ID " + admin_id + "?";
// variável com resposta da mensagem colocada na janela
var confirmacao = confirm(mensagem);

// se a confirmação for false o fluxo é interrompido
if (!confirmacao)
// elimar o evendo do botão clicado
event.preventDefault();
});
});
<?php $this->headScript()->captureEnd(); ?>
